# After changing this file, check it on:
#   http://lint.travis-ci.org/

language: python

# Run jobs on container-based infrastructure, can be overridden per job
dist: trusty

matrix:
  include:
    - os: linux
      python: 3.5
      env:
        - PYTHON_VERSION=3.5
    - os: linux
      python: 3.6
      env:
        - PYTHON_VERSION=3.6
    - os: linux
      #python: 3.7
      env:
        - TRAVIS_PYTHON_VERSION=3.7
        - PYTHON_VERSION=3.7

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a

  # Setup python environment
  - source devtools/travis-ci/before_install.sh
  - python -V
  - echo $PYTHON_VER
  - echo $TRAVIS_PYTHON_VERSION
  - echo $PYTHON_VERSION

install:
    # Create test environment for package
  - sed "s/python/python $PYTHON_VERSION*/g" devtools/conda-envs/base.yaml > tmp_base.yaml && conda env create -n test -f tmp_base.yaml && rm tmp_base.yaml
  - source activate test

    # Build and install package
  - python setup.py develop --no-deps

before_script:
  - python -V
  - conda list

script:
    # Get a bit of info first
  - python -c "import qcelemental; print(qcelemental.__version__)"

    # Run canonical tests
  - pytest -v --cov=qcelemental/ qcelemental/

notifications:
    email: false

after_success:
  - codecov
